
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.Position;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class AMonstername extends javax.swing.JFrame {
final void filllist(){
        try{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/onlinegame", "root",  "");
            Statement stmt = con.createStatement();
            String Query ="Select * FROM Monster";
            ResultSet rs = stmt.executeQuery(Query);
            DefaultListModel DLM = new DefaultListModel();
            while (rs.next()){
                DLM.addElement(rs.getString(1));
            }
            list1.setModel(DLM);
            
        }catch (SQLException ex){
        JOptionPane.showMessageDialog(null,ex.toString());
    }}
    public AMonstername() {
        initComponents();
        filllist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        searchtext = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        deletebtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        updatebtn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        list1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 205, 960);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 130, 300, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Monster Name :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 66, 110, 40);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 170, 300, 25);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(230, 210, 300, 25);

        updatebtn.setBackground(new java.awt.Color(255, 0, 0));
        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatebtn.setText("Modify");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatebtn);
        updatebtn.setBounds(540, 130, 300, 25);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(580, 70, 131, 30);

        searchtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtextActionPerformed(evt);
            }
        });
        jPanel1.add(searchtext);
        searchtext.setBounds(550, 10, 201, 30);

        searchbtn.setBackground(new java.awt.Color(255, 0, 0));
        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("Search By Name");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchbtn);
        searchbtn.setBounds(780, 10, 260, 25);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(1100, 70, 131, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Monster Level :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(980, 60, 110, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Monster Damage :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(456, 70, 130, 30);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(320, 70, 131, 30);

        deletebtn.setBackground(new java.awt.Color(255, 0, 0));
        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletebtn);
        deletebtn.setBounds(850, 130, 300, 25);

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Monster of higher damage Than Selected");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(540, 170, 299, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Monster Type:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(720, 60, 100, 50);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(820, 70, 131, 30);

        updatebtn1.setBackground(new java.awt.Color(255, 0, 0));
        updatebtn1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updatebtn1.setForeground(new java.awt.Color(255, 255, 255));
        updatebtn1.setText("List all Items");
        updatebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(updatebtn1);
        updatebtn1.setBounds(850, 170, 300, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/052_cd9964.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1645, 960);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list1ValueChanged
        try{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/onlinegame", "root",  "");
            Statement stmt = con.createStatement();
            String Query ="Select * FROM Monster WHERE Monstername ='"+list1.getSelectedValue()+"'";

            ResultSet rs = stmt.executeQuery(Query);
            while (rs.next()){
                jTextField1.setText(rs.getString(1));
                jTextField2.setText(rs.getString(2));
                jTextField3.setText(rs.getString(3));
                jTextField4.setText(rs.getString(4));
            }}catch (SQLException ex){
                JOptionPane.showMessageDialog(null,ex.toString());
            }
    }//GEN-LAST:event_list1ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/onlinegame", "root",  "");
            Statement stmt = (Statement) con.createStatement();
            if (jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()||jTextField4.getText().isEmpty()||jTextField3.getText().isEmpty()||jTextField4.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please fill all required fields.");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField1.setText("");
                jTextField4.setText("");

            }else{
                String insertionQuery= "INSERT INTO Monster  VALUES('"+ jTextField1.getText()  +"','" + jTextField2.getText() +"','"+ jTextField3.getText()+"','"+ jTextField4.getText()+"')";
                stmt.executeUpdate(insertionQuery);
                JOptionPane.showMessageDialog(null, "Monster has been created");
                filllist();

            }}catch  (SQLException e) {
                System.out.println("SQL Exception: "+ e.toString());}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GMPower g = new GMPower ();
        g.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        try{
             if (jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()||jTextField3.getText().isEmpty()||jTextField4.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please fill all required fields.");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField1.setText("");
                jTextField4.setText("");

            }else{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/onlinegame", "root",  "");
            Statement stmt = con.createStatement();
            String Query ="UPDATE Monster SET Monstername ='"+ jTextField1.getText()+"' ,MonsterDamage = '"+jTextField2.getText()+"',Monstertype = '"+jTextField3.getText()+"',Mosterlvl = '"+jTextField4.getText()+"' WHERE Monstername ='"+list1.getSelectedValue()+"'";
            stmt.execute(Query);

            JOptionPane.showMessageDialog(null, "Monster Updated");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            filllist();
             }
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void searchtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtextActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        int result=  list1.getNextMatch(searchtext.getText(), 0, Position.Bias.Forward);
        list1.setSelectedIndex(result);
    }//GEN-LAST:event_searchbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/onlinegame", "root",  "");
            Statement stmt = con.createStatement();
            String Query ="DELETE FROM Monster WHERE Monstername ='"+list1.getSelectedValue()+"'";
            stmt.execute(Query);

            JOptionPane.showMessageDialog(null, "Character Deleted");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
            jTextField3.setText("");
            
            filllist();

        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{ if (jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()||jTextField3.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Select An Monster .");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField1.setText("");

        }else{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/onlinegame", "root",  "");
            Statement stmt = con.createStatement();
            String Query =" Select Monstername From Monster  Where MonsterDamage > ALL(Select MonsterDamage From Monster Where Monstername ='"+ jTextField1.getText()+"')";
            ResultSet rs = stmt.executeQuery(Query);
            DefaultListModel DLM = new DefaultListModel();
            while (rs.next()){
                DLM.addElement(rs.getString(1));
            }
            list1.setModel(DLM);

            JOptionPane.showMessageDialog(null, "Monsters Listed");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");

        }
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void updatebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtn1ActionPerformed
        filllist();
    }//GEN-LAST:event_updatebtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JList list1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchtext;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton updatebtn1;
    // End of variables declaration//GEN-END:variables
}
